### ISSUE TITLE
[EPIC] Improved meta query performance

### ISSUE THREAD

**Issue by evanh** [getsentry/snuba#5695]
https://www.notion.so/sentry/Metrics-Autocomplete-Performance-d154d3a27d954847921f6b6be5f99d6a
```[tasklist]
### Tasks
- [x] Document potential solutions https://www.notion.so/sentry/Meta-Queries-Run-in-Snuba-a823dfea444b4573ba1838ff0c1ff985?pvs=4#e1f93027127942cda1b1b3e39f60d49e
- [ ] https://github.com/getsentry/snuba/pull/5681
- [ ] https://github.com/getsentry/snuba/pull/5680
- [ ] https://github.com/getsentry/snuba/pull/5687
- [x] Test query performance of V1 meta table https://www.notion.so/sentry/Meta-Queries-Run-in-Snuba-a823dfea444b4573ba1838ff0c1ff985?pvs=4#49138f36034e45768d30a43568bec0f1
- [ ] https://github.com/getsentry/snuba/issues/5696
- [ ] https://github.com/getsentry/snuba/pull/5715
- [ ] https://github.com/getsentry/snuba/issues/5723
- [ ] https://github.com/getsentry/snuba/pull/5716
- [ ] https://github.com/getsentry/snuba/pull/5726
- [ ] https://github.com/getsentry/snuba/pull/5733
- [ ] https://github.com/getsentry/snuba/pull/5734
- [ ] https://github.com/getsentry/snuba/pull/5735
- [ ] https://github.com/getsentry/snuba/pull/5746
- [ ] https://github.com/getsentry/snuba/pull/5747
- [ ] https://github.com/getsentry/snuba/pull/5748
- [ ] https://github.com/getsentry/snuba/pull/5749
- [ ] https://github.com/getsentry/snuba/pull/5759
- [ ] https://github.com/getsentry/snuba/pull/5760
- [ ] https://github.com/getsentry/snuba/pull/5769
- [ ] https://github.com/getsentry/snuba/pull/5784
- [ ] https://github.com/getsentry/snuba/pull/5797
```
