### ISSUE TITLE
[EPIC] MQL: Support composite queries for metric formulas

### ISSUE THREAD

**Issue by evanh** [getsentry/snuba#5738]
```[tasklist]
### Scoping: decide if we need to do these
- [ ] https://github.com/getsentry/snuba/issues/5739
- [ ] https://github.com/getsentry/snuba/issues/5740
- [ ] https://github.com/getsentry/snuba/issues/5741
- [ ] https://github.com/getsentry/snuba/issues/5742
```

```[tasklist]
### Parsing Step
- [ ] https://github.com/getsentry/snuba/issues/6062
- [ ] https://github.com/getsentry/snuba/issues/6063
- [ ] https://github.com/getsentry/snuba/issues/6059
- [ ] https://github.com/getsentry/snuba/issues/6060
- [ ] https://github.com/getsentry/snuba/issues/6061
```

```[tasklist]
### Subquery Generator
- [ ] https://github.com/getsentry/snuba/issues/6106
```
