### ISSUE TITLE
[EPIC] Time series storage evaluation

### ISSUE THREAD

**Issue by nikhars** [getsentry/snuba#5900]
We would like to evaluate different time series storage solutions in order to determine the optimal storage solution we would like to use for future time series data.

The sandbox on which the experiment is being run is in https://github.com/getsentry/terraform-sandboxes.private/tree/main/personal-sandbox/env/dev-nikhar

Some of the things which are specific to the components running inside the sandbox environment are in https://github.com/getsentry/tsdb-evaluation-sandbox

```[tasklist]
### Get data flowing into sandbox project
- [ ] https://github.com/getsentry/snuba/issues/5940
- [ ] https://github.com/getsentry/snuba/issues/5943
- [ ] https://github.com/getsentry/tsdb-evaluation-sandbox/issues/18
- [ ] https://github.com/getsentry/snuba/issues/5944
- [ ] https://github.com/getsentry/snuba/issues/5938
- [ ] https://github.com/getsentry/snuba/issues/5937
- [ ] https://github.com/getsentry/snuba/issues/5945
- [ ] https://github.com/getsentry/snuba/issues/5946
- [ ] https://github.com/getsentry/tsdb-evaluation-sandbox/issues/15
- [ ] https://github.com/getsentry/tsdb-evaluation-sandbox/issues/13
- [ ] https://github.com/getsentry/snuba/issues/6023
```

```[tasklist]
### Find better ways to store metrics data
- [ ] https://github.com/getsentry/snuba/issues/5995
- [ ] https://github.com/getsentry/snuba/issues/6002
- [ ] https://github.com/getsentry/snuba/issues/6003
- [ ] https://github.com/getsentry/snuba/issues/6033
```
```[tasklist]
### Query performance data gathering
- [ ] https://github.com/getsentry/snuba/issues/6012
```

**Comment by mcannizz** [comment]
@nikhars what is our current status?

**Comment by nikhars** [comment]
> @nikhars what is our current status?

1. Vector transformation code to hash metric names, tag keys and tag values is now known. What remains is testing it out locally with traffic. I want to ensure that the output doesn't leak any information outside of the SaaS environment. This is being actively worked on.
2. Clickhouse is deployed on the sandbox environment. Zookeeper still needs to be setup. Then the tables still need to be created on the clickhouse cluster. This is being actively worked on.
3. GKE has been deployed on the sandbox environment. It is needed to deploy vector in the sandbox which can read incoming data from US SaaS. This is done.
