### ISSUE TITLE
Enable dropping percentiles on per-use case and per-org bases

### ISSUE THREAD

**Issue by ayirr7** [getsentry/snuba#5912]
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/snuba/issues/5913
- [ ] https://github.com/getsentry/snuba/issues/5914
- [ ] https://github.com/getsentry/snuba/issues/5915
- [ ] https://github.com/getsentry/snuba/issues/5916
```

```[tasklist]
### Tasks
```
