### ISSUE TITLE
Deploy vector in US SaaS

### ISSUE THREAD

**Issue by nikhars** [getsentry/snuba#5938]
We have a working example of vector transformation which works locally [here](https://github.com/getsentry/tsdb-evaluation-sandbox/blob/main/vector/source/example_working_config.toml). We need to deploy something similar to this in US Saas via ~~k8s self-service pipeline~~ an ops ticket.

The sink of vector would be different than the working example. But we can start by creating the k8s deployment for vector. Some references are here https://vector.dev/docs/setup/installation/platforms/kubernetes/

This will ultimately be blocked on https://github.com/getsentry/snuba/issues/5939. But in the time being we can deploy on US SaaS with vector config with a blackhole [sink](https://vector.dev/docs/reference/configuration/sinks/blackhole/). Once the blocker is gone, we can change config to use the pub/sub sink or kafka sink.

```[tasklist]
### Milestones
- [ ] https://github.com/getsentry/ops/issues/10653
- [ ] https://github.com/getsentry/snuba/issues/5964
- [ ] https://github.com/getsentry/snuba/issues/5967
- [ ] https://github.com/getsentry/snuba/issues/5966
- [x] Scale vector pods in prod
- [ ] https://github.com/getsentry/snuba/issues/5968
- [ ] https://github.com/getsentry/snuba/issues/5969
```

**Comment by john-z-yang** [comment]
Vector is now deployed and writing to pub/sub
