### ISSUE TITLE
Create clickhouse tables for all metric types in the sandbox environment

### ISSUE THREAD

**Issue by nikhars** [getsentry/snuba#5946]
We have the VM's running in the sandbox which have clickhouse binary running on them.

Define the metrics schema which we want to use to experiment with and define the tables on both the clickhouse instances
```[tasklist]
### Tasks
- [ ] Create counters schema
- [ ] Create sets schema
- [ ] Create distributions schema
- [ ] Create gauges schema
```

**Comment by nikhars** [comment]
There are 2 trains of thoughts currently I have with respect to the tables we would want to create in clickhouse

## Aggregate tables
We do not employ codec's at all to the tables we have in production today. So we can use codec's to our advantage knowing the sorting order of the table and reduce our on disk footprint a lot. Here's a sample of the aggregated table we can use.

```sql
create table generic_metric_counters_aggregated_local
(
    use_case_id          LowCardinality(String),
    org_id               UInt64 CODEC(Delta, ZSTD),
    project_id           UInt64 CODEC(Delta, ZSTD),
    metric_name          String CODEC(ZSTD),
    granularity          UInt8 CODEC(DoubleDelta, ZSTD),
    timestamp            DateTime CODEC(Delta, ZSTD),
    retention_days       UInt16 CODEC(Delta, ZSTD),
    tags                 Nested (
                            key String,
                            value String
    ),
    value                AggregateFunction(sum, Float64)
)
    engine = AggregatingMergeTree PARTITION BY (retention_days, toMonday(timestamp))
        PRIMARY KEY (use_case_id, org_id, project_id, metric_name, granularity, timestamp)
        ORDER BY (use_case_id, org_id, project_id, metric_name, granularity, timestamp, tags, retention_days)
        TTL timestamp + toIntervalDay(retention_days);
```

tags are Nested instead of 2 separate array fields. I am not sure if that would be beneficial or not. Maybe in the first iteration we use the tags field as we have in prod itself

```
     `tags.key`           Array(String),
     `tags.value`        Array(String),
     _raw_tags_hash       Array(UInt64) materialized arrayMap((k, v) -> cityHash64(concat(k, '=', v)),
                                                             tags.key, tags.value)
```

## Raw tables
What if we did not have pre-aggregate values at all but stored all raw values for a given timestamp. Something similar to the below. The thing we do not know today is whether the cardinality of data is so high that certain timeseries don't get any values at all.

```sql
create table generic_metric_distributions_raw_local
(
    use_case_id               LowCardinality(String),
    org_id                    UInt64 CODEC(Delta, ZSTD),
    project_id                UInt64 CODEC(Delta, ZSTD),
    metric_name          String CODEC(ZSTD),
    timestamp                 DateTime CODEC(Delta, ZSTD),
    retention_days            UInt16  CODEC(Delta, ZSTD),
    `tags.key`                Array(String),
    `tags.value`          Array(String),
    set_values                Array(UInt64),
    count_value               Float64,
    distribution_values       Array(Float64),
    metric_type.         LowCardinality(String)
    timeseries_id             UInt32,
    partition                 UInt16,
    offset                    UInt64,
)
    engine = ReplacingMergeTree PARTITION BY toStartOfInterval(timestamp, toIntervalDay(3))
        ORDER BY (use_case_id, org_id, project_id, metric_id, timestamp)
        SETTINGS index_granularity = 8192;
```

**Comment by untitaker** [comment]
added some first schema in https://github.com/getsentry/tsdb-evaluation-sandbox/pull/16

(no raw table yet)

**Comment by untitaker** [comment]
I would like to first get the ingestion pipeline working "vertically" for one clickhouse schema before adding more of them.
